### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by xiaoheiccc** [wikiZ/RedGuard#10]
很久就star了，一直没来得及试试，最开始以为是类似C3的扩展C2，看了下介绍与用法，貌似只是做了前置流量的导向控制，没有否定作者工作成果的意思，只是感觉使用场景不是很大，建议扩展成C3那种(PS:因为我不会写，C3没有国内的通用通道，一直想弄一个国内能用的)，总之，风起大哥加油

**Comment by wikiZ** [comment]
感谢师傅的关注，RG主要是应用在红队攻防项目中，确实不太适用于日常渗透场景。

**Comment by JackeyLov5** [comment]
> 感谢师傅的关注，RG主要是应用在红队攻防项目中，确实不太适用于日常渗透场景。

师傅能细讲一下吗。没这方面的知识 想学习学习 。或者给点资料。谢谢

**Comment by wikiZ** [comment]
> > 感谢师傅的关注，RG主要是应用在红队攻防项目中，确实不太适用于日常渗透场景。
> 
> 师傅能细讲一下吗。没这方面的知识 想学习学习 。或者给点资料。谢谢

可以看下这个。
https://www.anquanke.com/post/id/291324

**Comment by JackeyLov5** [comment]
> https://www.anquanke.com/post/id/291324

谢谢师傅 提供的资料 但是域前置不是已死了吗？为什么现在还有大量的文章在说域前置呢。有没有现在能用的实际意义上的“域前置”的配置文章或者资料吗 不需要国内的的环节 当然如果国内环节是单独的也可以
还有其实我想知道为什么：RG主要是应用在红队攻防项目中，确实不太适用于日常渗透场景。
先谢谢师傅不吝赐教🙏

**Comment by wikiZ** [comment]
> > https://www.anquanke.com/post/id/291324
> 
> 谢谢师傅 提供的资料 但是域前置不是已死了吗？为什么现在还有大量的文章在说域前置呢。有没有现在能用的实际意义上的“域前置”的配置文章或者资料吗 不需要国内的的环节 当然如果国内环节是单独的也可以 还有其实我想知道为什么：RG主要是应用在红队攻防项目中，确实不太适用于日常渗透场景。 先谢谢师傅不吝赐教🙏

域前置在之前有人抢注的域名还是可以使用的，使用RedGuard可以通过自建节点实现域前置，也是通过header去转发流量，具体的你可以使用一下，之所以说不适用于日常渗透，主要是没有那么高的隐匿需求，如果你是正常挖src这样，当然如果你想给自己的攻击设施做隐藏也可以的。
