### ISSUE TITLE
大佬配置好之后

### ISSUE THREAD

**Issue by ksopen1** [wikiZ/RedGuard#14]
大佬配置好之后 使用crossC2上线linux是不行的

**Comment by wikiZ** [comment]
是下载的最新版本吗，通过crossc2上线没有问题的，如果本地测试还是不可以，可以去CrossC2提一下issue。

**Comment by ksopen1** [comment]
2023/09/23 04:38:51 http: panic serving ip:62326: runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
github.com/sleeyax/ja3rp/net/http.(*conn).serve.func1()
        github.com/sleeyax/ja3rp@v0.0.1/net/http/server.go:1801 +0xb9
panic({0x835c60, 0xcf45a0})
        runtime/panic.go:890 +0x263
RedGuard/core.MalleableFilter({0xc00002e921?, 0x20?}, 0xc0001da120)
        RedGuard/core/ProxyFilter.go:64 +0x78
RedGuard/core.ProxyFilterManger(0xc0001da120)
        RedGuard/core/ProxyFilter.go:190 +0xabc
RedGuard/core.(*baseHandle).ServeHTTP(0x0?, {0x9bbd70, 0xc0001fa000}, 0xc0001da120)
        RedGuard/core/ProxyHandler.go:114 +0x7c8
github.com/sleeyax/ja3rp/net/http.serverHandler.ServeHTTP({0xc0002081e0?}, {0x9bbd70, 0xc0001fa000}, 0xc0001da120)
        github.com/sleeyax/ja3rp@v0.0.1/net/http/server.go:2882 +0x443
github.com/sleeyax/ja3rp/net/http.(*conn).serve(0xc000108280, {0x9bc1a8, 0xc000208600})
        github.com/sleeyax/ja3rp@v0.0.1/net/http/server.go:1933 +0xb45
created by github.com/sleeyax/ja3rp/net/http.(*Server).Serve
        github.com/sleeyax/ja3rp@v0.0.1/net/http/server.go:3037 +0x4db
都配置好了之后 点马子之后上不来 Red提示这个

**Comment by ksopen1** [comment]
这个解决了 但是crossC2还是上不了linux crossC2无法配置hostheader和bind port

**Comment by wikiZ** [comment]
你直接去crossc2提issue就可以。

**Comment by wikiZ** [comment]
done
