### ISSUE TITLE
运行直接退出

### ISSUE THREAD

**Issue by virtualTS** [wikiZ/RedGuard#16]
ubuntu22.04运行最新版直接退出，无任何报错，默认配置也退出，重试了很多次才会启动成功，日志也完全看不出问题，后台启动也是秒断
![WechatIMG53](https://github.com/user-attachments/assets/4568a9da-c30b-4ce0-84f6-37bffdcbf37d)

**Comment by wikiZ** [comment]
你看下是不是你的80/443端口占用了。

**Comment by virtualTS** [comment]
> 你看下是不是你的80/443端口占用了。

想了下当时确实占用了443，但是我多次尝试启动的时候有启动成功的，我就没往这方面想，按理来说应该每次都不成功，这算bug吗？

**Comment by wikiZ** [comment]
启动成功了可能你正常开放的443估计就不好使了。

**Comment by virtualTS** [comment]
试了下确实是这个原因，感谢大佬解答
