### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Suhuan-zhen** [wikiZ/RedGuard#17]
作者你好，请问下我使用套cloudflare cdn隐藏c2的方式后再使用rg，当运行马时出现no cipher suite supported by both client and server错误。我也把cart都复制到了 cert-rsa下了。我在cloudflare上生成的证书是ecc格式，请问是这个的原因吗？

**Comment by wikiZ** [comment]
转换成crt格式证书再试一下

**Comment by wikiZ** [comment]
没问题我就先关闭了。
