### ISSUE TITLE
CS cannot go online when "HTTPS Host Header" is used

### ISSUE THREAD

**Issue by xiaosaoboy** [wikiZ/RedGuard#18]
# Set Host Header

When I set the Host to code.jquery.com, the generated payload will access code.jquery.com but not update.mic.tk. What is the reason?

<img width="436" alt="image" src="https://github.com/user-attachments/assets/8186d19a-e0d2-4171-9a41-d3db4c5dd810">

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/adb69778-c5e4-41c1-afaf-c69cdadf1bd0">

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/2c35c55b-162a-42d0-b06d-effde5c42693">

**Comment by wikiZ** [comment]
Please change the host address to ip

**Comment by xiaosaoboy** [comment]
Changed to ip, still doesn't work

<img width="436" alt="image" src="https://github.com/user-attachments/assets/eb4feae7-099b-499a-b927-22479d3f8072">

<img width="865" alt="image" src="https://github.com/user-attachments/assets/89d83dce-dfc9-4567-8073-c7fd67f9e68b">

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/83c89bd3-0087-436a-8389-95edaa4b2fb5">

**Comment by wikiZ** [comment]
你这咋生成的马，你这GET请求真到你设置的Header Host这个域名了好像，那肯定上不了，应该请求你C2服务器的指向域名或者IP，Header Host是配置文件伪造的这样。

**Comment by wikiZ** [comment]
How did you generate this? It seems that your GET request really goes to the domain name of the Header Host you set. It definitely cannot be accessed. You should request the domain name or IP pointed to by your C2 server. The Header Host is forged in the configuration file.
Sorry, I didn't notice your reply in Chinese:)

**Comment by xiaosaoboy** [comment]
I'm so sorry. I've been busy with some other stuff lately.  
I'm using the default profile(jquery) and have not changed the "Header Host".
The payload generated uses a stageless format.  Whether it's an IP or a domain, the first client's connection request is always correct, but the second request turns into the value of the Header Host.

**Comment by wikiZ** [comment]
So, have your problems been solved?

**Comment by xiaosaoboy** [comment]
I haven’t found a solution to the problem.
Perhaps you could try generating a beacon with v4.5, and you’ll encounter this issue just by modifying the Header Host.

**Comment by wikiZ** [comment]
Profile cannot specify the host header, because its priority is higher than the graphical interface listener configuration, cobaltstrike will use the profile first
