### ISSUE TITLE
Version Discrepancy in Latest Update

### ISSUE THREAD

**Issue by majid-derkaoui** [wikiZ/RedGuard#19]
Hi wikiZ ,

First, I'd like to thank you for your continuous efforts in developing the program. I wanted to bring to your attention a small issue with the latest release. It seems that the version you published was meant to be 24.06.18, but instead, the old version 23.08.21 was re-released.

I just wanted to point this out, and I’m sure it will be an easy fix. Thanks again for your great work, and I’m always looking forward to your new releases.

Best regards

**Comment by wikiZ** [comment]
ok

**Comment by wikiZ** [comment]
Thank you for your attention. After confirmation, the latest uploaded version of RedGuard only fixes the bug, but the version number is not changed.

**Comment by majid-derkaoui** [comment]
Hello wikiZ

Thank you for the quick clarification! I appreciate the explanation regarding the version number. It’s reassuring to know that the latest upload includes the bug fix, even if the version number remains the same.

Thanks again for all your hard work!

Best regards,
