### ISSUE TITLE
关于edge功能的bug

### ISSUE THREAD

**Issue by YyJqW** [wikiZ/RedGuard#20]
ProxyHandler.go第100行关于开启edge功能判断处，此处并未判断请求的host头是否匹配edgeTarget参数，导致发送过来的请求无论host值是什么都会通过过滤进入正常流量代理流程并根据rg开启之后接受到的第一次请求的结果缓存返回结果。
![image](https://github.com/user-attachments/assets/0e2f3681-3dda-4c65-a283-174659ef632d)
第一次请求为host不匹配edgeTarget的情况，即使第二次修改了host头为360.net，返回的结果仍为502，并且第一次本应该被跳转的请求也并没有跳转到360.net去
![image](https://github.com/user-attachments/assets/83ce91f1-08c1-4e1c-8d7d-1b13937b34f7)
第一次请求为host匹配的情况下，即使第二次host头不匹配，仍然转发到后端
![image](https://github.com/user-attachments/assets/9cb1d4a9-e5fb-4ec7-b83f-21edeb90e690)
![image](https://github.com/user-attachments/assets/ecfd9cb0-407f-44e8-9d2a-53ccc7d64fd3)
添加对host值的判断之后，功能恢复正常，不匹配的请求被正常跳转，匹配的请求正常转发到后端
![image](https://github.com/user-attachments/assets/8e6c8011-52f2-45ee-9f45-d0a2b1f12437)
![image](https://github.com/user-attachments/assets/bdb4a700-fa8c-4153-93eb-6485428150f6)

**Comment by wikiZ** [comment]
来篇文章，https://www.anquanke.com/post/id/278140
