### ISSUE TITLE
目前是不是不支持多个端口的监听

### ISSUE THREAD

**Issue by Chinakentgao** [wikiZ/RedGuard#3]
看了下好像是只能80 443 要对多个端口监听就不行了

**Comment by wikiZ** [comment]
不是，他是流量从80、443走，然后通过host分发多个监听器，没必要那么多啊，一个http\一个https，

**Comment by Chinakentgao** [comment]
我有个疑问比如我用云函数作为流量前置，在请求过来后不会经过80 443会被指向到真正CS的监听端口。但是启用的端口多了，就没办法用这种方式来防止探测的情况。

**Comment by wikiZ** [comment]
首先，一般不建议你用云函数做流量前置，这种方法很蠢，一方面是成本，一方面是没啥隐匿可言，场景放到RedGuard这里，所有流量都是从443和80走，这俩只不过是区分http或者https罢了，真正做你实际指向的是通过HOST跟代理的地址绑定区分的，也就是说流量从443来反向代理根据你的HOST判断到底代理到哪个地址，如果redguard和c2都在同一个vps那么你就可以设置这个代理地址为127.0.0.1：8080的形式，再配置服务器防火墙。

**Comment by wikiZ** [comment]
就理解为这个是键值对，可以配置无限多的后置监听器HostTarget    = {"360.net":"http://127.0.0.1:8080","360.com":"https://127.0.0.1:4433","hack.com":"8.8.8.8:1011"}这种形式。远程端口也行本地也行。

**Comment by Chinakentgao** [comment]
> 就理解为这个是键值对，可以配置无限多的后置监听器HostTarget = {"360.net":"[http://127.0.0.1:8080","360.com":"https://127.0.0.1:4433","hack.com":"8.8.8.8:1011"}这种形式。远程端口也行本地也行。](http://127.0.0.1:8080%22,%22360.com%22:%22https://127.0.0.1:4433%22,%22hack.com%22:%228.8.8.8:1011%22%7D%E8%BF%99%E7%A7%8D%E5%BD%A2%E5%BC%8F%E3%80%82%E8%BF%9C%E7%A8%8B%E7%AB%AF%E5%8F%A3%E4%B9%9F%E8%A1%8C%E6%9C%AC%E5%9C%B0%E4%B9%9F%E8%A1%8C%E3%80%82)

很感谢你的回复。对于云函数来说我觉得区别域名的方式在价格上云函数只要不设置低延迟价格不会比买一个域名来的贵。我是想着能够联动云函数达到更好的隐藏的效果。云函数直接省去买域名配置CDN的步骤我觉得还是性价比比较高

**Comment by wikiZ** [comment]
不是啊，不需要买啊。。。。以前各大厂商不验证域名归属大家都抢注了很多，云函数API网关有你的APPID，人家直接就能溯源到你，至于你说的结合，大家更多时候用的是域前置+RedG结合。

**Comment by Chinakentgao** [comment]
震惊 有没有具体的方法演示一下我得看看如果这么不安全我考虑更换域名的方式了 不用云函数了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月7日(星期二) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wikiZ/RedGuard] 目前是不是不支持多个端口的监听 (Issue #3)





 
不是啊，不需要买啊。。。。以前各大厂商不验证域名归属大家都抢注了很多，云函数API网关有你的APPID，人家直接就能溯源到你，至于你说的结合，大家更多时候用的是域前置+RedG结合。

**Comment by wikiZ** [comment]
https://www.anquanke.com/post/id/239640
https://www.anquanke.com/post/id/238142
