### ISSUE TITLE
有个改进建议！不知道新版本有没有加

### ISSUE THREAD

**Issue by Chinakentgao** [wikiZ/RedGuard#4]
就是现在最担心的就是沙箱的分析这块。对于使用CDN前置或者云函数的情况下RG就可能无法准确判断IP来源的可靠性了。就算在CDN处理过后携带真实IP给RG进行判断。由于判断的条件为域名的方式和C2请求合规来判断依然可能出现上线，这种情况过来的流量都是经过CDN中转后的IP即使内置很多沙箱IP也没办法判断出来是否来至沙箱的流量。再退一步来说通过在CDN进行白名单限制那过于麻烦。
    能否在RG上添加自定义头部判断。比如XFF头，在CDN或云函数处理后携带XFF头给RG。即使这个沙箱IP没有在内置库当中，
他只要不匹配白名单的要求依旧无法上线。

**Comment by wikiZ** [comment]
有的，ja3指纹识别，下个版本会上的

**Comment by sly9it** [comment]
Also going through (RG) is this an implementation of domain borrowing or it would be implemented here 


Thanks

**Comment by wikiZ** [comment]
The effect is so, but the function is more than that

**Comment by sly9it** [comment]
> The effect is so, but the function is more than that

Have you got a contact address i could reach you  through email or handle

Thanks

**Comment by wikiZ** [comment]
1402720815@qq.com
