### ISSUE TITLE
Can this be used on c2 redirectors

### ISSUE THREAD

**Issue by sly9it** [wikiZ/RedGuard#6]
Does this work on the c2 redirector though any tjoughst on that

**Comment by wikiZ** [comment]
RG is a c2 redirectors

**Comment by sly9it** [comment]
So its be used in the redirector server not the team server i guess


So its be used in the redirector server not the team server i guess

And socat to teamserver 



Then how's that don though

**Comment by sly9it** [comment]
*So its to be used in the redirector server not the team server i guess

**Comment by wikiZ** [comment]
Similar to the addition of a facility between the client and c2 for auditing traffic.

**Comment by sly9it** [comment]
Ok so just set it up on the teamsever yer ?

**Comment by wikiZ** [comment]
You will get everything you want to know from readme

**Comment by sly9it** [comment]
Did that snd understood all but was stock trying to to use RG on a redirector server and socat to the C2 my bad its just a hassle sometimes
