### ISSUE TITLE
开启RedGuard后报认证错误

### ISSUE THREAD

**Issue by MyPuppet** [wikiZ/RedGuard#8]
delete

**Comment by wikiZ** [comment]
你得绑定http host头

**Comment by MyPuppet** [comment]
> profile里配置header的host值为code.jquery.com了呀

**Comment by wikiZ** [comment]
可你配的是Facebook.com。。。。

**Comment by MyPuppet** [comment]
> "code.jquery.com":"http://127.0.0.1:8080"和"code.jquery.com":"https://127.0.0.1:8080"都试了。现在的配置是
{"code.jquery.com":"https://127.0.0.1:8443","facebook.com":"http://127.0.0.1:8080"}。

有点迷了，这个隐藏只是指隐藏监听🐎的端口嘛？不包含teamserver链接的端口是吗？
现在是想把teamserver也隐藏起来。

比如这样配置，然后在host对应的设置转发到8080.
java -XX:ParallelGCThreads=4 -Dcobaltstrike.server_port=8080 -Duser.language=en -Dcobaltstrike.server_bindto=127.0.0.1 -Djavax.net.ssl.keyStore=./cobaltstrike.store -Djavax.net.ssl.keyStorePassword=123456 -server -XX:+AggressiveHeap -XX:+UseParallelGC -classpath ./cobaltstrike.jar:. -Duser.language=en server.TeamServer $*

**Comment by wikiZ** [comment]
你得理解这是做啥的工具

**Comment by MyPuppet** [comment]
> 你得理解这是做啥的工具
相对理解。。 大佬，这个隐藏只能隐藏监听器的端口嘛？不能隐藏团队服务器的端口是嘛？我抓了cs连接团队服务器时没有发送HTTP请求，只做了DNS请求，所以没办法在此处添加头部的host也就没办法隐藏团队服务器的端口是嘛？

你看我理解的对不对。。  谢谢大佬晚上还在回复我。

**Comment by MyPuppet** [comment]
> 你得理解这是做啥的工具

而profile的配置只适用于监听器和客户端之间连接起作用，所以没有办法直接隐藏teamserver监听的端口。

大佬，你看我理解的对吗？

**Comment by wikiZ** [comment]
隐藏上线监听端口，是可以的，就是你在做vps防火墙上把实际监听端口给过滤，然后RG代理地址就是https://127.0.0.1:4433这种形式，本地转发过去是没问题的。

**Comment by MyPuppet** [comment]
> 

明白啦，谢啦

**Comment by MyPuppet** [comment]
> 隐藏上线监听端口，是可以的，就是你在做vps防火墙上把实际监听端口给过滤，然后RG代理地址就是[https://127.0.0.1:4433这种形式，本地转发过去是没问题的。](https://127.0.0.1:4433%E8%BF%99%E7%A7%8D%E5%BD%A2%E5%BC%8F%EF%BC%8C%E6%9C%AC%E5%9C%B0%E8%BD%AC%E5%8F%91%E8%BF%87%E5%8E%BB%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%E3%80%82)

谢啦！
