### ISSUE TITLE
Cannot parse C2concealer 

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [wikiZ/RedGuard#9]
Hey,

I tried using RedGuard on a redirector Server today. Unfortunately it was not able to parse my MalleableC2 profile correctly.

For example the following was not parsed correctly:

```
http-get "variant_1" {

        set uri "/test.css /testz.css";
}

```

As requests to the URL `/test.css` were not redirected but blocked.

Is that a bug?

Greetings

**Comment by wikiZ** [comment]
look your profile and RedGuard print info

**Comment by S3cur3Th1sSh1t** [comment]
Here you go. One full profile variane:


```
http-get "variant_5" {

        set uri "/lv.js";

        client {

                header "Host" "hostname.example.com";
                header "Connection" "close";
                header "Accept-Language" "fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5";

                metadata {
                        base64url;
                        base64;
                        prepend "woocommerce_cart_hash=";
                        header "Cookie";
                }


        }
        server {

                header "Connection" "close";
                header "Content-Type" "text/html";
                header "Server" "apache";

                output {
                        base64url;
                        base64;
                        prepend "<!DOCTYPE html><html class='no-js' lang='en-US'>  <head>    <meta http-equiv='X-UA-Compatible' content='IE=EDGE' />    <meta charset='utf-8'>    <meta name='viewport' content='width=device-width, initial-scale=1' />    <meta name='apple-itunes-app' conten$
                        print;
                }

        }

}
```


And the result from RedGuard:

![grafik](https://user-images.githubusercontent.com/27858067/185047531-13f33d55-8096-4d05-b3fd-4ec9fc5583f6.png)

**Comment by wikiZ** [comment]
You try this  https://github.com/wikiZ/CobaltStrike-Malleable-Profile

**Comment by S3cur3Th1sSh1t** [comment]
Ok. When changing `http-get "variant_5" {` to `http-get {` it works for the initial GET-Request. Seams, like your parser for the profile fails, when different http-get profile names are declared.

Also found another thing for `http-post` it does not parse the following correctly:

Non-Working example
```
http-post {

        set uri "/af, /media, /da";

```

![grafik](https://user-images.githubusercontent.com/27858067/185071826-1afc1313-8058-499f-9b79-7e287d5c1db8.png)

Some idea, why the parsing fails here?

**Comment by wikiZ** [comment]
Have a look your wireshark http request data，sir.

**Comment by wikiZ** [comment]
Have a look your wireshark http request data，sir.
